#[PARSER]
#  Name testdlq
#  Format regex
#  Regex ^(<log>[^ ]*) (<trigdlq>[^ ]*)$
#  Types log:string trigdlq:string

[SERVICE]
  Flush        1
  Log_Level    info
  Daemon       off
  Parsers_File parsers.conf

[INPUT]
  name                  tail
  refresh_interval      5
  path                  /var/log/test.log
  parser                testdlq
  read_from_head        true

[OUTPUT]
  Name http
  Match *
  Host data-prepper
  Port 2021
  URI /log/ingest
  Format json
  HTTP_User admin
  HTTP_Passwd admin
